### ISSUE TITLE
Disabling ‘--debug’ for Bridge can significantly reduce memory consumption

### ISSUE THREAD

**Issue by ltrsunny** [dubo-dubon-duponey/docker-roon#14]
which is quite friendly for low end embedded devices.

```
sed -i "s/\-\-debug//g" /boot/bin/RoonBridge/Bridge/RAATServer
sed -i "s/\-\-debug//g" /boot/bin/RoonBridge/Bridge/RoonBridgeHelper
sed -i "s/\-\-debug//g" /boot/bin/RoonBridge/Bridge/RoonBridge
```

**Comment by dubo-dubon-duponey** [comment]
Hey @ltrsunny 

I like the idea. Thanks. Will look into this soon.

**Comment by ltrsunny** [comment]
> Hey @ltrsunny
> 
> I like the idea. Thanks. Will look into this soon.

I also noticed that you are using `tail` to trace the log in entrypoint.sh, I disabled it in my container.

**Comment by dubo-dubon-duponey** [comment]
> > Hey @ltrsunny
> > I like the idea. Thanks. Will look into this soon.
> 
> I also noticed that you are using `tail` to trace the log in entrypoint.sh, I disabled it in my container.

Actually, you do not have to change the entrypoint script for that - you can just start the container with `--log-driver=none`

Quick note as well: the `work` branch is usually much more recent than `master` (doing a poor job at keeping this project friendly as I'm really my only user ;-)) - and `work` is what is being published on docker hub.

I'm curious about the memory aspect you mentioned wrt logs.
I'm running bridges on RPI3 and have not seen memory pressure coming from the bridge (or much being stored on the filesystem).

**Comment by ltrsunny** [comment]
> > > Hey @ltrsunny
> > > I like the idea. Thanks. Will look into this soon.
> > 
> > 
> > I also noticed that you are using `tail` to trace the log in entrypoint.sh, I disabled it in my container.
> 
> Actually, you do not have to change the entrypoint script for that - you can just start the container with `--log-driver=none`
> 
> Quick note as well: the `work` branch is usually much more recent than `master` (doing a poor job at keeping this project friendly as I'm really my only user ;-)) - and `work` is what is being published on docker hub.
> 
Yes, I pulled the image from docker hub. Your job is excellent! It solved a big problem in my development.
 
> I'm curious about the memory aspect you mentioned wrt logs. I'm running bridges on RPI3 and have not seen memory pressure coming from the bridge (or much being stored on the filesystem).

I am using your image on a dual-core ARMv7 with 128MB RAM.  Removing '--debug' can reduce about 10~30MB RAM usage (under openwrt) which is very sensitive for the whole system.
And theoretically, any unnecessary process is harmful for sound in a hifi system.

**Comment by dubo-dubon-duponey** [comment]
Ok! 128MB is not a lot indeed - I'm just using RPI myself.

Agreed on minimizing footprint anyhow.
I'll push an update soon-ish.

**Comment by dubo-dubon-duponey** [comment]
Interesting / relevant discussion here: https://community.roonlabs.com/t/roon-server-settings-turn-off-debug-logs/133901/57

**Comment by dubo-dubon-duponey** [comment]
Ok, pushed a new version with:
- updated roon bridge version
- `--debug` removed

As usual it's on the `work` branch, not `master` - and on Docker Hub (currently tagged `bridge-latest` and `bridge-bullseye-2022-04-01`).

Rough memory measurements - before:

```
11232 2000      4.2 RoonBridgeHelper --debug --gc=sgen --server RoonBridgeHelper.exe
11240 2000      4.0 RAATServer --debug --gc=sgen --server RAATServer.exe
11124 2000      3.4 RoonBridge --debug --gc=sgen --server RoonBridge.exe
```

Now:
```
19736 2000      3.9 RoonBridgeHelper --gc=sgen --server RoonBridgeHelper.exe
19768 2000      3.8 RAATServer --gc=sgen --server RAATServer.exe
19600 2000      2.7 RoonBridge --gc=sgen --server RoonBridge.exe
```

This suggests (on this machine) about 10-15MB of memory saved, which is aligned with what you suggested.

Going to close this ticket as resolved now.

Thank you @ltrsunny  for the suggestion.

**Comment by ltrsunny** [comment]
> > > Hey @ltrsunny
> > > I like the idea. Thanks. Will look into this soon.
> > 
> > 
> > I also noticed that you are using `tail` to trace the log in entrypoint.sh, I disabled it in my container.
> 
> Actually, you do not have to change the entrypoint script for that - you can just start the container with `--log-driver=none`
> 

With `--log-driver=none`, `tail` is still running there.
![image](https://user-images.githubusercontent.com/49466661/168564362-7fd89494-dce3-401d-95ff-08853af684a3.png)

**Comment by dubo-dubon-duponey** [comment]
What `--log-driver=none` does is prevent docker from logging any of stdout into log files. Therefore, `tail` in that case will basically pipe into `/dev/null` instead of log files under `/var/lib`.

If you are concerned about reducing IO, you should definitely disable logging for your containers, especially the chatty ones. Given Roon is also (always) logging to files, and again if IO is a concern, you should mount a nullfs in Roon log location.

You are right that the tail processes will still be there - though the resources consumed should be extremely low (especially compared to the overhead of podman/containerd/containers) - which is why I do not want to remove them by default in the default image.

**Comment by ltrsunny** [comment]
> 

Make sense

**Comment by ltrsunny** [comment]
> What `--log-driver=none` does is prevent docker from logging any of stdout into log files. Therefore, `tail` in that case will basically pipe into `/dev/null` instead of log files under `/var/lib`.
> 
> If you are concerned about reducing IO, you should definitely disable logging for your containers, especially the chatty ones. Given Roon is also (always) logging to files, and again if IO is a concern, you should mount a nullfs in Roon log location.
> 
> You are right that the tail processes will still be there - though the resources consumed should be extremely low (especially compared to the overhead of podman/containerd/containers) - which is why I do not want to remove them by default in the default image.

Make sense.
